"""Project Memory Manager Implementation.

This module implements the ProjectMemoryInterface to provide
multi-level project memory management.
"""

import os
import re
import asyncio
import aiofiles
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional, Set
import logging

from derisk_core.config.home import get_derisk_home

from . import (
    MemoryPriority,
    MemorySource,
    MemoryLayer,
    ProjectMemoryConfig,
    ImportDirective,
    MemoryConsolidationConfig,
    ProjectMemoryInterface,
)

logger = logging.getLogger(__name__)


class ProjectMemoryManager(ProjectMemoryInterface):
    """Manages multi-level project memories.

    This implementation provides:
    1. Multi-layer memory with priority-based merging
    2. @import directive resolution
    3. Auto-memory writing
    4. Memory consolidation
    5. Agent-specific memory support

    Example:
        config = ProjectMemoryConfig(project_root="/path/to/project")
        manager = ProjectMemoryManager()
        await manager.initialize(config)

        # Build context for an agent
        context = await manager.build_context(agent_name="my_agent")

        # Write to auto-memory
        await manager.write_auto_memory("Important decision made: use PostgreSQL")
    """

    # Standard memory file names
    MEMORY_FILES = {
        "main": "MEMORY.md",
        "rules": "RULES.md",
        "default_agent": "AGENTS/DEFAULT.md",
    }

    # User memory location
    USER_MEMORY_DIR = get_derisk_home()

    def __init__(self):
        """Initialize the memory manager."""
        self._config: Optional[ProjectMemoryConfig] = None
        self._layers: Dict[MemoryPriority, MemoryLayer] = {}
        self._initialized = False
        self._import_cache: Dict[str, str] = {}
        self._pending_writes: List[Dict[str, Any]] = []

    async def initialize(self, config: ProjectMemoryConfig) -> None:
        """Initialize the project memory system.

        This scans all memory sources and builds the layer structure.

        Args:
            config: Configuration for the memory system
        """
        self._config = config

        # Create memory directory structure if needed
        await self._ensure_directory_structure()

        # Initialize memory layers
        self._layers = {
            MemoryPriority.AUTO: MemoryLayer(name="auto", priority=MemoryPriority.AUTO),
            MemoryPriority.USER: MemoryLayer(name="user", priority=MemoryPriority.USER),
            MemoryPriority.PROJECT: MemoryLayer(name="project", priority=MemoryPriority.PROJECT),
            MemoryPriority.MANAGED: MemoryLayer(name="managed", priority=MemoryPriority.MANAGED),
            MemoryPriority.SYSTEM: MemoryLayer(name="system", priority=MemoryPriority.SYSTEM),
        }

        # Scan and load all memory sources
        await self._scan_memory_sources()

        self._initialized = True
        logger.info(f"ProjectMemory initialized for {config.project_root}")

    async def _ensure_directory_structure(self) -> None:
        """Ensure the .derisk directory structure exists."""
        if not self._config:
            return

        memory_path = self._config.memory_path

        # Create main directories
        dirs_to_create = [
            memory_path,
            memory_path / "AGENTS",
            memory_path / "KNOWLEDGE",
            memory_path / "MEMORY.LOCAL",
            memory_path / "MEMORY.LOCAL" / "sessions",
        ]

        for dir_path in dirs_to_create:
            if not dir_path.exists():
                dir_path.mkdir(parents=True, exist_ok=True)
                logger.debug(f"Created directory: {dir_path}")

        # Create default files if they don't exist
        await self._create_default_files()

    async def _create_default_files(self) -> None:
        """Create default memory files if they don't exist."""
        if not self._config:
            return

        memory_path = self._config.memory_path

        # Default MEMORY.md content
        memory_file = memory_path / self.MEMORY_FILES["main"]
        if not memory_file.exists():
            default_content = """# Project Memory

This file contains project-level memory that helps the AI assistant understand your project.

## Project Overview

<!-- Describe your project here -->

## Key Decisions

<!-- Record important decisions made during development -->

## Conventions

<!-- Document coding conventions and patterns -->

## Known Issues

<!-- Track known issues and their workarounds -->

---
> This file is auto-generated by Derisk. Edit it to add project-specific context.
"""
            await self._write_file(memory_file, default_content)
            logger.info(f"Created default MEMORY.md at {memory_file}")

        # Default .gitignore for MEMORY.LOCAL
        gitignore_file = memory_path / ".gitignore"
        if not gitignore_file.exists():
            gitignore_content = """# Local memory files (not committed to Git)
MEMORY.LOCAL/
sessions/
auto-memory.md
"""
            await self._write_file(gitignore_file, gitignore_content)

    async def _scan_memory_sources(self) -> None:
        """Scan and load all memory sources from all layers."""
        if not self._config:
            return

        # Scan user-level memories
        if self._config.enable_user_memory:
            await self._scan_user_memories()

        # Scan project-level memories
        if self._config.enable_project_memory:
            await self._scan_project_memories()

        # Scan auto-memories
        if self._config.enable_auto_memory:
            await self._scan_auto_memories()

    async def _scan_user_memories(self) -> None:
        """Scan user-level memories from ~/.derisk/."""
        user_dir = self.USER_MEMORY_DIR
        if not user_dir.exists():
            return

        # Look for user-level memory files
        user_memory = user_dir / "MEMORY.md"
        if user_memory.exists():
            content = await self._read_file(user_memory)
            source = MemorySource(
                path=user_memory,
                priority=MemoryPriority.USER,
                scope="user",
                content=content,
                metadata={"type": "user_memory"}
            )
            self._layers[MemoryPriority.USER].add_source(source)
            logger.debug(f"Loaded user memory from {user_memory}")

    async def _scan_project_memories(self) -> None:
        """Scan project-level memories from .derisk/."""
        if not self._config:
            return

        memory_path = self._config.memory_path
        if not memory_path.exists():
            return

        # Main memory file
        main_memory = memory_path / self.MEMORY_FILES["main"]
        if main_memory.exists():
            content = await self._read_file(main_memory)
            imports = await self._extract_imports(content)
            source = MemorySource(
                path=main_memory,
                priority=MemoryPriority.PROJECT,
                scope="project",
                content=content,
                imports=imports,
                metadata={"type": "main_memory"}
            )
            self._layers[MemoryPriority.PROJECT].add_source(source)

        # Rules file
        rules_file = memory_path / self.MEMORY_FILES["rules"]
        if rules_file.exists():
            content = await self._read_file(rules_file)
            source = MemorySource(
                path=rules_file,
                priority=MemoryPriority.PROJECT,
                scope="project",
                content=content,
                metadata={"type": "rules"}
            )
            self._layers[MemoryPriority.PROJECT].add_source(source)

        # Knowledge directory
        knowledge_dir = memory_path / "KNOWLEDGE"
        if knowledge_dir.exists():
            for kb_file in knowledge_dir.glob("*.md"):
                content = await self._read_file(kb_file)
                source = MemorySource(
                    path=kb_file,
                    priority=MemoryPriority.PROJECT,
                    scope="project",
                    content=content,
                    metadata={"type": "knowledge", "name": kb_file.stem}
                )
                self._layers[MemoryPriority.PROJECT].add_source(source)

        # Agent-specific memories
        agents_dir = memory_path / "AGENTS"
        if agents_dir.exists():
            for agent_file in agents_dir.glob("*.md"):
                content = await self._read_file(agent_file)
                source = MemorySource(
                    path=agent_file,
                    priority=MemoryPriority.PROJECT,
                    scope="agent",
                    content=content,
                    metadata={"type": "agent_config", "agent_name": agent_file.stem}
                )
                self._layers[MemoryPriority.PROJECT].add_source(source)

    async def _scan_auto_memories(self) -> None:
        """Scan auto-generated memories."""
        if not self._config:
            return

        auto_memory_file = self._config.auto_memory_path
        if auto_memory_file.exists():
            content = await self._read_file(auto_memory_file)
            source = MemorySource(
                path=auto_memory_file,
                priority=MemoryPriority.AUTO,
                scope="auto",
                content=content,
                metadata={"type": "auto_memory"}
            )
            self._layers[MemoryPriority.AUTO].add_source(source)

    async def _extract_imports(self, content: str) -> List[str]:
        """Extract @import directives from content."""
        directives = ImportDirective.parse(content)
        return [d.raw_path for d in directives]

    async def build_context(
        self,
        agent_name: Optional[str] = None,
        session_id: Optional[str] = None,
    ) -> str:
        """Build the complete context string.

        This merges all memory layers by priority and resolves
        all @import directives.

        Args:
            agent_name: Optional agent name for agent-specific memory
            session_id: Optional session ID for session-specific memory

        Returns:
            The merged context string
        """
        if not self._initialized:
            return ""

        context_parts = []

        # Process layers from lowest to highest priority
        for priority in sorted(MemoryPriority):
            layer = self._layers.get(priority)
            if not layer or not layer.sources:
                continue

            layer_content = await self._build_layer_content(
                layer,
                agent_name=agent_name,
                session_id=session_id
            )

            if layer_content:
                context_parts.append(f"## {layer.name.upper()} MEMORY\n\n{layer_content}")

        # Join all layers
        full_context = "\n\n---\n\n".join(context_parts)

        # Resolve all imports
        resolved_context = await self.resolve_imports(full_context)

        return resolved_context

    async def _build_layer_content(
        self,
        layer: MemoryLayer,
        agent_name: Optional[str] = None,
        session_id: Optional[str] = None,
    ) -> str:
        """Build content for a single layer.

        This filters and merges sources within a layer based on
        agent_name and session_id.
        """
        contents = []

        for source in layer.sources:
            # Filter by agent name if specified
            if agent_name:
                source_type = source.metadata.get("type")
                agent_in_source = source.metadata.get("agent_name", "").upper()

                # Skip agent configs for other agents
                if source_type == "agent_config" and agent_in_source != agent_name.upper():
                    continue

                # Include DEFAULT.md for all agents
                if source_type == "agent_config" and agent_in_source == "DEFAULT":
                    contents.append(f"### Default Agent Config\n\n{source.content}")
                    continue

            # Skip auto-memories that don't match session
            if source.scope == "session" and session_id:
                if source.metadata.get("session_id") != session_id:
                    continue

            # Add source content
            if source.content:
                header = f"### {source.name}"
                contents.append(f"{header}\n\n{source.content}")

        return "\n\n".join(contents)

    async def get_memory_layers(self) -> List[MemoryLayer]:
        """Get all memory layers sorted by priority.

        Returns:
            List of MemoryLayer objects from lowest to highest priority
        """
        return [self._layers[p] for p in sorted(MemoryPriority) if p in self._layers]

    async def write_auto_memory(
        self,
        content: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> str:
        """Write to auto-memory.

        Auto-memory is automatically generated and has the lowest priority.
        It's typically written after conversations or important decisions.

        Args:
            content: The memory content to write
            metadata: Optional metadata (importance, tags, etc.)

        Returns:
            The ID or path of the written memory
        """
        if not self._config:
            raise RuntimeError("ProjectMemory not initialized")

        auto_memory_path = self._config.auto_memory_path

        # Ensure the parent directory exists
        auto_memory_path.parent.mkdir(parents=True, exist_ok=True)

        # Format the entry
        timestamp = datetime.now().isoformat()
        importance = metadata.get("importance", 0.5) if metadata else 0.5
        tags = metadata.get("tags", []) if metadata else []

        entry = f"""
## Auto Memory Entry - {timestamp}

{content}

- Importance: {importance}
- Tags: {', '.join(tags) if tags else 'none'}

---
"""
        # Append to the file
        existing_content = ""
        if auto_memory_path.exists():
            existing_content = await self._read_file(auto_memory_path)

        new_content = existing_content + entry
        await self._write_file(auto_memory_path, new_content)

        # Update the layer
        source = MemorySource(
            path=auto_memory_path,
            priority=MemoryPriority.AUTO,
            scope="auto",
            content=new_content,
            metadata=metadata or {}
        )
        self._layers[MemoryPriority.AUTO].sources = [source]

        return str(auto_memory_path)

    async def resolve_imports(self, content: str, depth: int = 0) -> str:
        """Resolve all @import directives in content.

        Args:
            content: The content containing @import directives
            depth: Current recursion depth (for cycle detection)

        Returns:
            Content with all imports resolved
        """
        if depth > (self._config.max_import_depth if self._config else 5):
            logger.warning(f"Import depth {depth} exceeds maximum, stopping recursion")
            return content

        directives = ImportDirective.parse(content)

        for directive in directives:
            raw_path = directive.raw_path

            # Check cache first
            if raw_path in self._import_cache:
                imported_content = self._import_cache[raw_path]
            else:
                # Resolve the path
                resolved_path = await self._resolve_import_path(raw_path)

                if resolved_path and resolved_path.exists():
                    imported_content = await self._read_file(resolved_path)
                    # Recursively resolve imports in the imported content
                    imported_content = await self.resolve_imports(imported_content, depth + 1)
                    self._import_cache[raw_path] = imported_content
                else:
                    imported_content = f"<!-- @import {raw_path} - file not found -->"
                    logger.warning(f"Import file not found: {raw_path}")

            # Replace the @import directive with the content
            import_line = f"@import {raw_path}"
            content = content.replace(import_line, imported_content)

        return content

    async def _resolve_import_path(self, raw_path: str) -> Optional[Path]:
        """Resolve an import path to an actual file path.

        Supports relative paths and special prefixes:
        - @user/ - User-level memory (~/.derisk/)
        - @project/ - Project-level memory (./.derisk/)
        - @knowledge/ - Knowledge directory
        """
        if not self._config:
            return None

        memory_path = self._config.memory_path

        # Handle special prefixes
        if raw_path.startswith("@user/"):
            user_path = self.USER_MEMORY_DIR / raw_path[6:]
            return user_path if user_path.exists() else None

        if raw_path.startswith("@project/"):
            project_path = memory_path / raw_path[9:]
            return project_path if project_path.exists() else None

        if raw_path.startswith("@knowledge/"):
            kb_path = memory_path / "KNOWLEDGE" / raw_path[11:]
            return kb_path if kb_path.exists() else None

        # Try relative to memory directory
        relative_path = memory_path / raw_path
        if relative_path.exists():
            return relative_path

        # Try with .md extension
        if not raw_path.endswith(".md"):
            md_path = memory_path / f"{raw_path}.md"
            if md_path.exists():
                return md_path

        return None

    async def get_agent_memory(self, agent_name: str) -> Optional[MemorySource]:
        """Get agent-specific memory.

        Args:
            agent_name: The name of the agent

        Returns:
            MemorySource for the agent, or None if not found
        """
        project_layer = self._layers.get(MemoryPriority.PROJECT)
        if not project_layer:
            return None

        for source in project_layer.sources:
            if source.metadata.get("agent_name", "").upper() == agent_name.upper():
                return source

        # Fall back to DEFAULT.md
        for source in project_layer.sources:
            if source.metadata.get("agent_name", "").upper() == "DEFAULT":
                return source

        return None

    async def consolidate_memories(
        self,
        config: Optional[MemoryConsolidationConfig] = None,
    ) -> Dict[str, Any]:
        """Consolidate and clean up memories.

        This removes duplicates, summarizes old entries, and
        organizes the memory structure.

        Args:
            config: Optional consolidation configuration

        Returns:
            Statistics about the consolidation process
        """
        config = config or MemoryConsolidationConfig()
        stats = {
            "entries_removed": 0,
            "entries_summarized": 0,
            "duplicates_removed": 0,
            "total_size_before": 0,
            "total_size_after": 0,
        }

        # Get auto-memory content
        if not self._config:
            return stats

        auto_memory_path = self._config.auto_memory_path
        if not auto_memory_path.exists():
            return stats

        content = await self._read_file(auto_memory_path)
        stats["total_size_before"] = len(content)

        # Parse entries (section by timestamp)
        entries = self._parse_memory_entries(content)

        # Remove duplicates
        if config.deduplicate:
            unique_entries = []
            seen_content = set()
            for entry in entries:
                # Normalize content for comparison
                normalized = re.sub(r'\s+', ' ', entry['content'].lower().strip())
                if normalized not in seen_content:
                    seen_content.add(normalized)
                    unique_entries.append(entry)
                else:
                    stats["duplicates_removed"] += 1
            entries = unique_entries

        # Filter by importance and age
        filtered_entries = []
        for entry in entries:
            importance = entry.get('importance', 0.5)
            age_days = (datetime.now() - entry.get('timestamp', datetime.now())).days

            if importance >= config.min_importance or age_days <= config.max_age_days:
                filtered_entries.append(entry)
            else:
                stats["entries_removed"] += 1

        # Reconstruct the file
        new_content = self._reconstruct_memory(filtered_entries)
        stats["total_size_after"] = len(new_content)

        # Write the consolidated content
        await self._write_file(auto_memory_path, new_content)

        return stats

    def _parse_memory_entries(self, content: str) -> List[Dict[str, Any]]:
        """Parse memory entries from content."""
        entries = []

        # Split by entry markers
        pattern = r'## Auto Memory Entry - ([\d\-T:.]+)\n\n(.*?)(?=## Auto Memory Entry|$)'
        matches = re.findall(pattern, content, re.DOTALL)

        for timestamp_str, entry_content in matches:
            try:
                timestamp = datetime.fromisoformat(timestamp_str)
            except ValueError:
                timestamp = datetime.now()

            entries.append({
                'timestamp': timestamp,
                'content': entry_content.strip(),
                'importance': self._extract_importance(entry_content),
            })

        return entries

    def _extract_importance(self, content: str) -> float:
        """Extract importance value from entry content."""
        match = re.search(r'Importance:\s*([\d.]+)', content)
        if match:
            try:
                return float(match.group(1))
            except ValueError:
                pass
        return 0.5

    def _reconstruct_memory(self, entries: List[Dict[str, Any]]) -> str:
        """Reconstruct memory content from entries."""
        lines = ["# Auto Memory\n\nThis file contains automatically generated memories.\n\n"]

        for entry in entries:
            timestamp_str = entry['timestamp'].isoformat()
            lines.append(f"## Auto Memory Entry - {timestamp_str}\n\n")
            lines.append(entry['content'])
            lines.append("\n\n---\n\n")

        return ''.join(lines)

    # File I/O helpers

    async def _read_file(self, path: Path) -> str:
        """Read file content asynchronously."""
        try:
            async with aiofiles.open(path, 'r', encoding='utf-8') as f:
                return await f.read()
        except Exception as e:
            logger.error(f"Failed to read {path}: {e}")
            return ""

    async def _write_file(self, path: Path, content: str) -> None:
        """Write file content asynchronously."""
        try:
            async with aiofiles.open(path, 'w', encoding='utf-8') as f:
                await f.write(content)
        except Exception as e:
            logger.error(f"Failed to write {path}: {e}")
            raise

    # Session memory methods

    async def write_session_memory(
        self,
        session_id: str,
        content: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> str:
        """Write session-specific memory.

        Args:
            session_id: The session ID
            content: The memory content
            metadata: Optional metadata

        Returns:
            The path to the session memory file
        """
        if not self._config:
            raise RuntimeError("ProjectMemory not initialized")

        session_path = self._config.session_path / f"{session_id}.md"
        session_path.parent.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().isoformat()
        entry = f"""# Session Memory - {session_id}

Last updated: {timestamp}

{content}
"""
        await self._write_file(session_path, entry)

        # Add to session layer
        source = MemorySource(
            path=session_path,
            priority=MemoryPriority.AUTO,
            scope="session",
            content=entry,
            metadata={"session_id": session_id, **(metadata or {})}
        )

        # Update or add to AUTO layer
        auto_layer = self._layers[MemoryPriority.AUTO]
        auto_layer.sources = [s for s in auto_layer.sources
                             if s.metadata.get("session_id") != session_id]
        auto_layer.add_source(source)

        return str(session_path)

    async def get_session_memory(self, session_id: str) -> Optional[str]:
        """Get session-specific memory content.

        Args:
            session_id: The session ID

        Returns:
            The session memory content, or None if not found
        """
        if not self._config:
            return None

        session_path = self._config.session_path / f"{session_id}.md"
        if session_path.exists():
            return await self._read_file(session_path)
        return None