"""
DeliverFileTool - Sandbox File Delivery Tool

Marks sandbox files as deliverables and generates delivery links for user access.

Core functionality:
1. Read file content from sandbox
2. Upload to storage (local/OSS) to get persistent link
3. Generate d-attach component for frontend display
4. Register to AgentFileSystem for subsequent management
"""

import logging
import os
from typing import Dict, Any, Optional

from .base import SandboxToolBase
from ...base import ToolCategory, ToolRiskLevel, ToolEnvironment, ToolSource
from ...metadata import ToolMetadata
from ...context import ToolContext
from ...result import ToolResult

logger = logging.getLogger(__name__)

_DELIVER_FILE_PROMPT = """Mark sandbox files as deliverables and generate delivery links.

**Use Cases:**
- Report files generated by shell_exec need to be delivered to users
- Analysis script output result files need to be persisted
- Any sandbox files that need to be delivered as final outputs

**Workflow:**
1. Read file content from sandbox
2. Upload to storage (local/OSS) to get persistent link
3. Generate d-attach component for frontend display
4. Register to AgentFileSystem for subsequent management

**Difference from create_file:**
- `create_file`: Create new file and write content
- `deliver_file`: Mark existing sandbox file as deliverable

**Recommended Usage:**
```
# 1. Generate report using shell_exec
shell_exec(command="python3 analyze.py --output /home/user/report.md")

# 2. View report content to confirm
view(path="/home/user/report.md")

# 3. Mark as deliverable
deliver_file(path="/home/user/report.md", description="Risk Analysis Report")
```

**Privacy Compliance Policy:**
Follow "hide specific penalty reasons", "traceable but not identifiable" and "security instruction restrictions" principles:
1. Hide interception reasons: When encountering risk control, anti-money laundering, regulatory interceptions, do not explain specific rules, use general technical terms like "system policy restrictions".
2. Minimize privacy information: Must remove personal privacy information such as names, phone numbers, emails, addresses, only retain internal IDs like user ID, merchant ID, order number, transaction number for troubleshooting, ensuring traceability but not user identity identification.
3. Prohibit high-risk operations and sensitive information disclosure: Do not execute commands involving penetration testing, malicious attacks, vulnerability exploitation; do not expose, disseminate or require users to provide any critical tokens, keys, certificates, passwords and other sensitive security credentials."""


def _validate_string_param(
    value: Optional[str], field_name: str, allow_empty: bool = False
) -> Optional[str]:
    """Simple parameter validation, returns error message."""
    if value is None:
        if allow_empty:
            return None
        return f"Error: {field_name} cannot be empty"
    if not isinstance(value, str):
        return f"Error: {field_name} must be a string"
    if not allow_empty and not value.strip():
        return f"Error: {field_name} cannot be an empty string"
    return None


def _get_mime_type(file_name: str) -> str:
    """Get MIME type based on file extension"""
    import mimetypes

    mime_type, _ = mimetypes.guess_type(file_name)
    return mime_type or "application/octet-stream"


class DeliverFileTool(SandboxToolBase):
    """Sandbox file delivery tool"""

    def _define_metadata(self) -> ToolMetadata:
        return ToolMetadata(
            name="deliver_file",
            display_name="Deliver File",
            description=_DELIVER_FILE_PROMPT,
            category=ToolCategory.SANDBOX,
            risk_level=ToolRiskLevel.LOW,
            source=ToolSource.SYSTEM,
            requires_permission=False,
            timeout=60,
            environment=ToolEnvironment.SANDBOX,
            tags=["file", "deliver", "output", "sandbox", "attachment"],
            author="openderisk",
        )

    def _define_parameters(self) -> Dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string",
                    "description": "Absolute path of the file in sandbox",
                },
                "description": {
                    "type": "string",
                    "description": "File description (optional, for explaining the purpose of the deliverable)",
                },
                "file_type": {
                    "type": "string",
                    "enum": ["deliverable", "report", "data", "log", "other"],
                    "default": "deliverable",
                    "description": "File type classification: deliverable, report, data, log, other",
                },
            },
            "required": ["path"],
        }

    async def execute(
        self, args: Dict[str, Any], context: Optional[ToolContext] = None
    ) -> ToolResult:
        """Execute file delivery"""
        path = args.get("path")
        description = args.get("description", "")
        file_type = args.get("file_type", "deliverable")

        # Validate parameters
        error = _validate_string_param(path, "path", allow_empty=False)
        if error:
            return ToolResult.fail(error=error, tool_name=self.name)

        error = _validate_string_param(description, "description", allow_empty=True)
        if error:
            return ToolResult.fail(error=error, tool_name=self.name)

        # Check sandbox availability
        client = self._get_sandbox_client(context)
        if client is None:
            return ToolResult.fail(
                error="Error: Current task has not initialized sandbox environment, cannot deliver file",
                tool_name=self.name,
            )

        # Normalize path
        from derisk.sandbox.sandbox_utils import (
            normalize_sandbox_path,
            detect_path_kind,
        )

        try:
            sandbox_path = normalize_sandbox_path(client, path)
        except ValueError as exc:
            return ToolResult.fail(error=f"Error: {exc}", tool_name=self.name)

        # Check if file exists
        try:
            path_kind = await detect_path_kind(client, sandbox_path)
            if path_kind == "none":
                return ToolResult.fail(
                    error=f"Error: File does not exist: {sandbox_path}",
                    tool_name=self.name,
                )
            if path_kind == "dir":
                return ToolResult.fail(
                    error=f"Error: Path is a directory, not a file: {sandbox_path}",
                    tool_name=self.name,
                )
        except Exception as exc:
            return ToolResult.fail(
                error=f"Error: Failed to check file: {exc}",
                tool_name=self.name,
            )

        # Get file name
        file_name = os.path.basename(sandbox_path)

        # Use file name as description if empty
        if not description or not description.strip():
            description = f"Deliverable file: {file_name}"

        # Get MIME type
        mime_type = _get_mime_type(file_name)

        # Try to upload to storage and generate delivery URL
        delivery_url = None
        object_path = None
        file_size = None

        # Method 1: Use sandbox's built-in file upload (if available)
        if hasattr(client, "file") and client.file:
            try:
                # Try to upload to OSS if configured
                if hasattr(client.file, "upload_to_oss"):
                    oss_file = await client.file.upload_to_oss(sandbox_path)
                    if oss_file:
                        delivery_url = oss_file.temp_url
                        object_path = oss_file.object_name
                        logger.info(
                            f"[deliver_file] OSS upload successful: {delivery_url}"
                        )
            except Exception as exc:
                logger.warning(f"[deliver_file] OSS upload failed: {exc}")

            # Try to read file info for size
            try:
                file_info = await client.file.read(sandbox_path)
                if file_info:
                    content = getattr(file_info, "content", None)
                    if content:
                        file_size = len(
                            content.encode("utf-8")
                            if isinstance(content, str)
                            else content
                        )
            except Exception as exc:
                logger.warning(f"[deliver_file] Failed to read file info: {exc}")

        # Method 2: Generate local file URL for local sandbox
        if not delivery_url:
            # For local sandbox, generate a local file reference
            # The URL will be handled by the file service endpoint
            conversation_id = self._get_conversation_id(context)
            if hasattr(client, "work_dir") and client.work_dir:
                # Construct a local file reference
                local_file_path = os.path.join(
                    client.work_dir, sandbox_path.lstrip("/")
                )
                if os.path.exists(local_file_path):
                    file_size = os.path.getsize(local_file_path)
                    # Use derisk-fs URI format for local files
                    delivery_url = f"local://{sandbox_path}"
                    logger.info(f"[deliver_file] Local file reference: {delivery_url}")

        # Method 3: Check if sandbox has storage client
        if not delivery_url:
            # Try to get storage client from context
            storage_client = None
            if context:
                if isinstance(context, dict):
                    storage_client = context.get("file_storage_client")
                else:
                    storage_client = context.config.get("file_storage_client")

            if storage_client and hasattr(storage_client, "save_file"):
                try:
                    # Read file content first
                    if hasattr(client, "file") and client.file:
                        file_info = await client.file.read(sandbox_path)
                        if file_info and file_info.content:
                            import io

                            content_bytes = (
                                file_info.content.encode("utf-8")
                                if isinstance(file_info.content, str)
                                else file_info.content
                            )
                            file_data = io.BytesIO(content_bytes)

                            # Save to storage
                            uri = storage_client.save_file(
                                bucket="deliverables",
                                file_name=file_name,
                                file_data=file_data,
                            )
                            delivery_url = uri
                            object_path = uri
                            file_size = len(content_bytes)
                            logger.info(
                                f"[deliver_file] Storage save successful: {uri}"
                            )
                except Exception as exc:
                    logger.warning(f"[deliver_file] Storage save failed: {exc}")

        # Build result
        result_parts = [
            f"✅ File marked as deliverable: {sandbox_path}",
            f"📋 Description: {description.strip()}",
            f"📁 Type: {file_type}",
        ]

        # Check if delivery URL was generated
        if not delivery_url:
            logger.warning(
                f"[deliver_file] No delivery URL generated for {sandbox_path}. "
                f"File exists in sandbox but is not accessible via web URL."
            )
            result_parts.append(
                "\n⚠️ **Note: File marked, but no accessible preview/download link generated.**\n"
                "The file is available in the sandbox workspace."
            )
            return ToolResult.ok(output="\n".join(result_parts), tool_name=self.name)

        # Generate d-attach component
        try:
            from derisk_serve.agent.file_io.dattach_utils import render_dattach

            dattach_content = render_dattach(
                file_name=file_name,
                file_url=delivery_url,
                file_type=file_type,
                object_path=object_path,
                preview_url=delivery_url,
                download_url=delivery_url,
                description=description.strip(),
                mime_type=mime_type,
                file_size=file_size,
            )
            result_parts.append("\n\n**Deliverable File:**")
            result_parts.append(dattach_content)
        except ImportError:
            # Fallback if dattach_utils not available
            result_parts.append(f"\n\n**Download URL:** {delivery_url}")
        except Exception as exc:
            logger.warning(f"[deliver_file] d-attach rendering failed: {exc}")
            result_parts.append(f"\n\n**Download URL:** {delivery_url}")

        # Add storage path info
        if object_path:
            result_parts.append(f"\n**Storage Path:** {object_path}")

        return ToolResult.ok(output="\n".join(result_parts), tool_name=self.name)
